{{- if gt (len .Values.ingress.domains) 0 }}
{{- $global := . }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
{{- if .Values.ingress.acme }}
    kubernetes.io/tls-acme: "true"
{{- end }}
  name: {{ template "fullname" . }}
spec:
{{- if .Values.ingress.acme }}
  tls:
  - secretName: {{ template "fullname" $global }}
    hosts:
{{- range $domain := .Values.ingress.domains }}
    - {{ $domain }}
{{- end }}
{{- end }}
  rules:
{{- range $domain := .Values.ingress.domains }}
  - host: {{ $domain }}
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" $global }}
          servicePort: {{ $global.Values.service.externalPort }}
        path: /
{{- end }}
{{- end }}
